# Generated by Django 3.1.5 on 2021-10-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_Name', models.CharField(max_length=50)),
                ('Team_Name', models.CharField(max_length=3)),
                ('GP', models.IntegerField()),
                ('MIN', models.FloatField()),
                ('FGM', models.FloatField()),
                ('FGA', models.FloatField()),
                ('FG_PCT', models.FloatField()),
                ('FG3M', models.FloatField()),
                ('FTM', models.FloatField()),
                ('FTA', models.FloatField()),
                ('FT_PCT', models.FloatField()),
                ('REB', models.FloatField()),
                ('AST', models.FloatField()),
                ('STL', models.FloatField()),
                ('BLK', models.FloatField()),
                ('TOV', models.FloatField()),
                ('PTS', models.FloatField()),
                ('Pos', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
